version: '3.8'

services:
  job-portal:
    build: .
    ports:
      - "8000:8000"
    environment:
      - MONGO_URI=mongodb+srv://BACCHA:U4tgwjHNikm1vD2n@mvc.xrjek.mongodb.net/JobPortal?retryWrites=true&w=majority&appName=MVC
      - JWT_SECRET=JOB-PORTAL
    depends_on:
      - mongo

  mongo:
    image: mongo
    container_name: mongo
    ports:
      - "27017:27017"
    volumes:
      - mongodb_data:/data/db

volumes:
  mongodb_data:
